// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApw5BoWccfXe034yGKt9KvKfvlAayjFOw',
    appId: '1:284290443519:web:5f2467222a19bdcf1b44ca',
    messagingSenderId: '284290443519',
    projectId: 'hello-d8a45',
    authDomain: 'hello-d8a45.firebaseapp.com',
    storageBucket: 'hello-d8a45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChPUD7rY1JQYSJdnANoo8fImVEjVbJyo',
    appId: '1:284290443519:android:b8c923d4f880d79e1b44ca',
    messagingSenderId: '284290443519',
    projectId: 'hello-d8a45',
    storageBucket: 'hello-d8a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEtsj2X0n2Rg0kgwVL85gmPKcmKsrU7o',
    appId: '1:284290443519:ios:cbacf2aa94ec75be1b44ca',
    messagingSenderId: '284290443519',
    projectId: 'hello-d8a45',
    storageBucket: 'hello-d8a45.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEEtsj2X0n2Rg0kgwVL85gmPKcmKsrU7o',
    appId: '1:284290443519:ios:abb50c555c72b6cd1b44ca',
    messagingSenderId: '284290443519',
    projectId: 'hello-d8a45',
    storageBucket: 'hello-d8a45.appspot.com',
    iosBundleId: 'com.example.pushnotification.RunnerTests',
  );
}
